on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: mohzulfikar/hello-world-composite-action@v2
        with:
          who-to-greet: 'The Octocat Mona'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

